name = "Minesweeper"
uuid = "bddff93e-315a-4f57-a84c-5c46674f3d29"
authors = ["Lilith Hafner <Lilith.Hafner@gmail.com> and contributors"]
version = "0.0.0"

[deps]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
Gtk = "4c0ca9eb-093a-5379-98c5-f87ac0bbbf44"

[compat]
Cairo = "1"
Gtk = "1"
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
